---
- name: Install packages
  hosts: loadbalancers
  become: true
  tasks:
  - name: Install Apache httpd package
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Star Apache Service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true


- name: Install packages on Web Servers
  hosts: webservers
  become: true
  tasks:
  - name: Install Apache and PHP packages
    ansible.builtin.yum:
      name:
        - httpd
        - php
      state: present

  - name: Start Apache Service
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true
  